name: firebase_invite
description: A new Flutter project.
version: 0.0.3
author:
homepage:

dependencies:
  flutter:
    sdk: flutter


flutter:
  plugin:
    androidPackage: pl.lukaszbyjos.firebaseinvite
    pluginClass: FirebaseInvitePlugin

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"
